### ISSUE TITLE
Use classes instead of changing styles directly

### ISSUE THREAD

**Issue by MartinBspheroid** [orhun/ratzilla#11]
This will improve performance by injecting a generated stylesheet into the web app and toggling classes on each cell span to apply styles instead of directly manipulating their style attributes. 
This approach will leverage the browser's optimized CSS engine for applying styles, and reduce overhead compared to inline styles, especially when dealing with a large number of elements.
For example: add styles for all basic ANSI colors for font color and background color, and then toggle classes on each element to apply the desired color (including transparent for no color).

```css 
/* Generated stylesheet */
.fg-black {
  color: black;
}
.bg-black {
  background-color: black;
}
.fg-red {
  color: red;
}
.bg-red {
  background-color: red;
}
```

Ideas/Features:

- Generate a stylesheet with all basic ansi colors for font color and background color.
- Inject it into a document on startup.
- Toggle classes on each element to apply the desired color (including transparent for no color).
